# HERE are the configs for demo
# Most of the configs are for better visualization in Rerun

# Disable other visualization
# for debug visualization
# if you need debuging in rerun, open this. This will give you plenty of debug information
show_debug_entities: false
# set false for long time data collecting, because the long run rerun will have lag
#  https://github.com/rerun-io/rerun/issues/7678
show_local_entities: True

# global_mapping floor height in rerun
floor_height: 0.0 # -1.2

# height of related bbox visualization in rerun
related_height: -0.1

# Robot height
# this one change the path height in rerun
robot_height: 0.8

# path visualization radius in rerun
# this one change the path width
path_radii: 0.03
action_path_color: [255, 0, 0]
global_path_color: [0, 255, 0]

# Filter the local objects around the ceiling for better visualization
filter_ceiling: true
ceiling_height: 2.5
ceiling_threshold: 0.2

# For global path planning
# real world nav can use this mode if the nav path is not ideal
use_directional_path: false

# For action path planning
# real world nav can use this mode if the nav path is not ideal
# for simulation, this one is not necessary, recomend to use false
use_remove_sharp_turns: true


# show global obj 3d bbox in rerun
show_global_map_3d_bbox: false

# restrict unknown labels
restrict_unknown_labels: true

# Save the calculcated local_path, global_path, and action_path
save_all_path: true

# World axis rotation changing config
# Setting RPY here to adjust the mapped results with XYZ axis
# Origin
world_roll: 0.0
world_pitch: 0.0
world_yaw: 0.0

# lab device default adjustment
# world_roll: 0.0
# world_pitch: 20.0
# world_yaw: 0.0

# long bottle keyborad
# world_roll: 0.0
# world_pitch: 19.0
# world_yaw: -1.2

# black backpack
# world_roll: 0.0
# world_pitch: 18.0
# world_yaw: -3.7

# w1-l1-office
# world_roll: 0.0
# world_pitch: -3.0
# world_yaw: 9.0

# w2-l3-hallway-1
# world_roll: -0.8
# world_pitch: -1.0
# world_yaw: 5.5

# w2-l3-hallway-2
# world_roll: 0.0
# world_pitch: -2.0
# world_yaw: 7.0

# w1-l2-office
# world_roll: 0.0
# world_pitch: 0.0
# world_yaw: 9.0

# Follower camera config in rerun for visualization
# left,right; up down; forwardbackward
follower_translation: [0.8, -1.0, -2.0]
follower_roll: -20.0
follower_pitch: -20.0
follower_yaw: 0.0

follower_translation2: [0.8, -3.2, -6.0]
follower_roll2: -25.0
follower_pitch2: -5.0
follower_yaw2: 0.0

# back view setting
# follower_translation: [0.0, -1.0, -2.0]
# follower_roll: -20.0
# follower_pitch: 0.0
# follower_yaw: 0.0

# side view setting
# follower_translation: [-0.8, -1.0, -2.0]
# follower_roll: -20.0
# follower_pitch: 20.0
# follower_yaw: 0.0